# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Dan Wu
tagline:          'A Jekyll theme'
description:      'Hi, I&rsquo;m Dan - an Associate Product Manager at <a href="http://www.braintreepayments.com" target="_blank">Braintree</a>.<br><br/> This is where I&rsquo;ll be everything and anything I find interesting. Enjoy!'
url:              http://danwu.me

author:
  name:           'Dan Wu'
  url:            https://twitter.com/itsdanwu

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde